openapi: 3.0.2
info:
  "$ref": "./components/info.yml"

tags:
  "$ref": "../../common/tags.yml"

servers:
  "$ref": "../../common/servers.yml"

paths:
  "$ref": "./components/paths.yml"

x-amazon-apigateway-binary-media-types:
  - "multipart/form-data"
  - "image/jpeg"

x-amazon-apigateway-gateway-responses:
  "$ref": "./components/default_responses.yml"

x-amazon-apigateway-cors:
  "$ref": "./components/cors.yml"

x-amazon-apigateway-importexport-version: "1.0"

components:
  securitySchemes:
    "$ref": "./components/security_schemes.yml"

  schemas:
    "$ref": "../../common/schemas.yml"

  headers:
    "$ref": "../../common/headers.yml"
