package configuration;

public class DynamoDBUser {
    public static final String USER_ID = "userId",
            ADDRESS_ID = "addressId",
            NAME = "name",
            FIRST_NAME = "firstName",
            LAST_NAME = "lastName",
            COMPANY_NAME = "companyName",
            COMPANY_PREFIX = "companyPrefix",
            FEDERAL_TAX = "federalTax",
            RG = "rg",
            EMAIL = "email",
            PHONE = "phone",
            MOBILE_PHONE = "mobilePhone",
            JWT = "jwt",
            ONE_TIME_PASSWORD = "oneTimePassword",
            NOTIFY = "notify",
            DISABILITY = "disability",
            PASSWORD = "password",
            LOCALE = "locale",
            AVG_PUNCTUAL = "avgPunctual",
            AVG_LABOR = "avgLabor",
            AVG_PRESENTATION = "avgPresentation",
            AVG_ATTITUDE = "avgAttitude",
            OPERATOR_TYPE = "operatorType",
            IS_DRIVER = "isDriver",
            LICENSE = "license",
            CATEGORY = "category",
            EMITER = "emiter",
            BIRTH_DATE = "birthDate",
            LAST_NUMBER = "lastNumber",
            LAST_NUMBER_UNITLOAD = "lastNumberUnitload",
            LAST_NUMBER_ORDER = "lastNumberOrder",
            LAST_NUMBER_SHIPMENT = "lastNumberShipment",
            VEHICLE_ID = "vehicleId",
            PIC_USER = "picUser";
}
