import { i18n } from 'boot/i18n';

const routes = [
    {
        path: '/',
        name: 'layout',
        component: () => import('layouts/MainLayout.vue'),
        children: [
            {
                path: 'home',
                name: 'home',
                component: () => import('src/pages/oldJson/HomeOld.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.home'),
                    icon: 'mdi-home',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.home',
                },
            },
            {
                path: 'shipments',
                name: 'shipments',
                component: () => import('src/pages/oldJson/ShipmentsOld.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.shipments'),
                    icon: 'mdi-package-variant',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.shipments',
                },
            },
            {
                path: 'Unitloads',
                name: 'Unitloads',
                component: () => import('src/pages/oldJson/UnitloadsOld.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.unitloads'),
                    icon: 'mdi-cube-outline',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.unitloads',
                },
            },
            {
                path: 'driver',
                name: 'driver',
                component: () => import('src/pages/oldJson/SumDriverDelivery.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.driver'),
                    icon: 'mdi-truck',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.driver',
                },
            },
            {
                path: 'clientOld',
                name: 'clientOld',
                component: () => import('src/pages/oldJson/ClientsOld.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.clientOld'),
                    icon: 'mdi-account-multiple',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.clientOld',
                },
            },
            {
                path: 'shipmentsAndUnitloads',
                name: 'shipmentsAndUnitloads',
                component: () => import('pages/ShipmentsAndUnitloads.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.shipmentsAndUnitloads'),
                    icon: 'mdi-file-document-outline',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.shipmentsAndUnitloads',
                },
            },
            {
                path: 'client',
                name: 'client',
                component: () => import('src/pages/Clients.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.client'),
                    icon: 'mdi-account-multiple',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.client',
                },
            },
            {
                path: 'user',
                name: 'user',
                component: () => import('src/pages/Users.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.user'),
                    icon: 'mdi-account-multiple',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.user',
                },
            },
            {
                path: 'logs',
                name: 'logs',
                component: () => import('src/pages/Logs.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.logs'),
                    icon: 'mdi-file-document-outline',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.logs',
                },
            },
            {
                path: 'billing',
                name: 'billing',
                component: () => import('pages/Billing.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.billing'),
                    icon: 'mdi-currency-usd',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.billing',
                },
            },
            {
                path: 'allBilling',
                name: 'allBilling',
                component: () => import('pages/AllBilling.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.allBilling'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.allBilling',
                },
            },
            {
                path: 'yardconf01',
                name: 'yardconf01',
                component: () => import('src/components/yard/YardConfig01.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.YardConfig01'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.Yard',
                },
            },
            {
                path: 'yardconf02',
                name: 'yardconf02',
                component: () => import('src/components/yard/YardConfig02.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.YardConfig02'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.Yard',
                },
            },
            {
                path: 'yardconf03',
                name: 'yardconf03',
                component: () => import('src/components/yard/YardConfig03.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.YardConfig03'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.Yard',
                },
            },
            {
                path: 'map01',
                name: 'map01',
                component: () => import('src/components/yard/Maps01.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.Map01'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.map',
                },
            },
            {
                path: 'map02',
                name: 'map02',
                component: () => import('src/components/yard/Map02.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.Map02'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.map2',
                },
            },
            {
                path: 'map03',
                name: 'map03',
                component: () => import('src/components/yard/Map03.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.Map03'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.map3',
                },
            },
            {
                path: 'yardhome',
                name: 'yardhome',
                component: () => import('src/pages/YardHome.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.yardHome'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.yardhome',
                },
            },
            {
                path: 'design',
                name: 'design',
                component: () => import('src/pages/DesignDrew.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.design'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.design',
                },
            },
            {
                path: 'test',
                name: 'test',
                component: () => import('src/pages/testes/Testes.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.test'),
                    icon: 'mdi-file-document',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.testes',
                },
            },
            {
                path: 'about',
                name: 'about',
                component: () => import('src/pages/About.vue'),
                meta: {
                    showDrawer: true,
                    title: i18n.global.t('routes.about'),
                    icon: 'mdi-information-outline',
                    iconColor: 'orange',
                    requiresAuth: true,
                    label: 'routes.about',
                },
            },
        ],
    },
    {
        name: 'login',
        path: '/login',
        component: () => import('pages/Login.vue'),
        meta: {
            label: 'routes.login',
        },
    },
    {
        path: '/:catchAll(.*)*',
        component: () => import('pages/ErrorNotFound.vue'),
        meta: {
            label: 'routes.notFound',
        },
    },
];

export default routes;
