const routes = [
  {
    path: "/",
    name: "layout",
    component: () => import("layouts/MainLayout.vue"),
    children: [
      {
        path: "home",
        name: "home",
        component: () => import("src/pages/IndexPage.vue"),
        meta: {
          showDrawer: true,
          title: "home",
          icon: "mdi-home",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.home",
        },
      },
      {
        path: "design",
        name: "design",
        component: () => import("src/pages/DesignDrew.vue"),
        meta: {
          showDrawer: true,
          title: "design",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "Design",
        },
      },
      {
        path: "page2",
        name: "page2",
        component: () => import("src/pages/TestePage.vue"),
        meta: {
          showDrawer: true,
          title: "page2",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "driver",
        name: "driver",
        component: () => import("src/pages/DriverPage.vue"),
        meta: {
          showDrawer: true,
          title: "Driver",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "dock",
        name: "dock",
        component: () => import("src/pages/DockPage.vue"),
        meta: {
          showDrawer: true,
          title: "Dock",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "trailer",
        name: "trailer",
        component: () => import("src/pages/TrailerPage.vue"),
        meta: {
          showDrawer: true,
          title: "Trailer",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "vehicle",
        name: "vericle",
        component: () => import("src/pages/VehiclePage.vue"),
        meta: {
          showDrawer: true,
          title: "Vehicle",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "destinator",
        name: "destinator",
        component: () => import("src/pages/DestinatorPage.vue"),
        meta: {
          showDrawer: true,
          title: "Destinator",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "route",
        name: "route",
        component: () => import("src/pages/RoutePlanningPage.vue"),
        meta: {
          showDrawer: true,
          title: "Planejamento de Rotas",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "cds",
        name: "cds",
        component: () => import("src/pages/CDsPage.vue"),
        meta: {
          showDrawer: true,
          title: "CDs",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "timeDelivery",
        name: "timeDelivery",
        component: () => import("src/pages/TimeForDelivery.vue"),
        meta: {
          showDrawer: true,
          title: "Tempo de Trajéto",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "dockConstraints",
        name: "dockConstraints",
        component: () => import("src/pages/DockConstraints.vue"),
        meta: {
          showDrawer: true,
          title: "Restrições Dock",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.sd",
        },
      },
      {
        path: "routeOptmized",
        name: "outeOptmized",
        component: () => import("src/pages/RouteOptimized.vue"),
        meta: {
          showDrawer: true,
          title: "Roteirizador",
          icon: "mdi-package-variant",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.s",
        },
      },
      {
        path: "yardconf01",
        name: "yardconf01",
        component: () => import("src/components/yard/YardConfig01.vue"),
        meta: {
          showDrawer: true,
          title: "routes.YardConfig01",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.Yard",
        },
      },
      {
        path: "yardconf02",
        name: "yardconf02",
        component: () => import("src/components/yard/YardConfig02.vue"),
        meta: {
          showDrawer: true,
          title: "routes.YardConfig02",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.Yard",
        },
      },
      {
        path: "map01",
        name: "map01",
        component: () => import("src/components/yard/DockController.vue"),
        meta: {
          showDrawer: true,
          title: "routes.Map01",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.map",
        },
      },
      {
        path: "map02",
        name: "map02",
        component: () => import("src/components/yard/Map02Component.vue"),
        meta: {
          showDrawer: true,
          title: "routes.Map02",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.map2",
        },
      },
      {
        path: "yardhome",
        name: "yardhome",
        component: () => import("src/pages/YardHome.vue"),
        meta: {
          showDrawer: true,
          title: "routes.YardHome",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.yardhome",
        },
      },
      {
        path: "moreDraw",
        name: "moredraw",
        component: () => import("src/pages/ImageUpdate.vue"),
        meta: {
          showDrawer: true,
          title: "routes.ImageUpdate",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.moreDraw",
        },
      },
      {
        path: "yardRoute",
        name: "yardRoute",
        component: () => import("src/components/yard/InputStart.vue"),
        meta: {
          showDrawer: true,
          title: "routes.YardRoute",
          icon: "mdi-file-document",
          iconColor: "orange",
          requiresAuth: true,
          label: "routes.yardRoute",
        },
      },
    ],
  },
  {
    name: "login",
    path: "/login",
    component: () => import("pages/LoginPage.vue"),
    meta: {
      label: "routes.login",
    },
  },
  {
    path: "/:catchAll(.*)*",
    component: () => import("pages/ErrorNotFound.vue"),
    meta: {
      label: "routes.notFound",
    },
  },
];

export default routes;
